// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootShop.DataAccess;

namespace bootShop.DataAccess.Migrations
{
    [DbContext(typeof(bootShopDbContext))]
    partial class bootShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefonlar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilgisayarlar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Konsollar"
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 885, DateTimeKind.Local).AddTicks(4139),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "IPhone 13",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 887, DateTimeKind.Local).AddTicks(3515),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "Samsung S22",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 887, DateTimeKind.Local).AddTicks(3555),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "Xiaomi",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 887, DateTimeKind.Local).AddTicks(3559),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "Apple Mac",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 887, DateTimeKind.Local).AddTicks(3561),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "Lenovo",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 4, 3, 22, 19, 20, 887, DateTimeKind.Local).AddTicks(3564),
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/550/10986386784306.jpg/format:webp",
                            Name = "XBox",
                            Price = 1200.0
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.HasOne("bootShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
